package ru.grape.course.controllers.commons;

public enum DaoAction {
    CHECK_IF_LOGIN_EXISTS,
    GET_ALL_EXERCISES,
    GET_CLIENT_BY_ACCOUNT_ID,
    UPDATE_CLIENT,
    ADD_CLIENT_SERVICE,
    GET_SERVICES_BY_CLIENT_ID,
    DELETE_CLIENT_SERVICE_BY_EXERCISE_ID,
    UPDATE_RATE_BY_CLIENT_ID,
    GET_USERS,
    GET_GOALS,
    GET_EXPERTS,
    UPDATE_GOALS,
    DELETE_CLIENT_BY_LOGIN,
    ADD_CLIENT_HAVING_LOGIN_PASSWORD_ROLE,
    ADD_CLIENT,
    GET_RATES,
    GET_ALL_CLIENTS,
    GET_ALL_SERVICES,
    GET_RATE_BY_CLIENT_ID,
    GIVE_ME_HASH
}
